// Package constant ...
package constant

const (
	// TrxStatusPending ...
	TrxStatusPending = "PENDING"
	// TrxStatusProcessing ...
	TrxStatusProcessing = "PROCESSING"
	// TrxStatusFailed ...
	TrxStatusFailed = "FAILED"
	// TrxStatusSuccess ...
	TrxStatusSuccess = "SUCCESS"
)

const (
	// TrxDirectionDebit ...
	TrxDirectionDebit = "DEBIT"
	// TrxDirectionCredit ...
	TrxDirectionCredit = "CREDIT"
)
